dist: xenial

language: php

php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "nightly"

env:
  - CONTAO_VERSION=~4.9.0
  - CONTAO_VERSION=~4.10.0

matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core-bundle contao/core-bundle $CONTAO_VERSION --no-update
  - >
    if [ "x${TRAVIS_TAG}" != "x" ]; then
      export COMPOSER_ROOT_VERSION=${TRAVIS_TAG}
    else
      export COMPOSER_ROOT_VERSION=$([[ ${TRAVIS_BRANCH} =~ (hotfix|release)/([0-9.]*(-(alpha|beta|rc)[0-9]+)?) ]] \
        && echo ${BASH_REMATCH[2]} \
        || echo dev-${TRAVIS_BRANCH})
    fi
  - echo "Using root version ${COMPOSER_ROOT_VERSION}"
  - >
    echo "PHP version: ${TRAVIS_PHP_VERSION}";
    if [ "x${TRAVIS_PHP_VERSION}" == "xnightly" ]; then
      travis_retry composer update --ignore-platform-reqs --prefer-dist --no-interaction --no-suggest
    else
      travis_retry composer update --prefer-dist --no-interaction --no-suggest
    fi

script: vendor/bin/phpcq -v -o github-action -o default

git:
  depth: false

cache:
  directories:
    - vendor
