parameters:
  netzmacht.contao_toolkit.alias_generator.default: 'netzmacht.contao_toolkit.data.alias_generator.factory.default_factory'

services:
  _defaults:
    public: false

  netzmacht.contao_toolkit.listeners.get_template_helpers:
    class: Netzmacht\Contao\Toolkit\View\Template\Subscriber\GetTemplateHelpersListener
    arguments:
      - '@netzmacht.contao_toolkit.assets_manager'
      - '@translator'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_toolkit.view.get_template_helpers', method: 'handle' }

  netzmacht.contao_toolkit.listeners.create_formatter_subscriber:
    class: Netzmacht\Contao\Toolkit\Dca\Formatter\Subscriber\CreateFormatterSubscriber
    arguments:
      - []
      - []
      - []
      - '@netzmacht.contao_toolkit.dca.formatter.options'
    tags:
      - { name: 'kernel.event_listener', event: 'netzmacht.contao_toolkit.dca.create_formatter', method: 'handle' }

  netzmacht.contao_toolkit.listeners.merge_hook_listeners:
    class: Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\Listener\MergeHookListenersListener
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.callback_invoker'
      - []

  netzmacht.contao_toolkit.listeners.register_component_decorators:
    class: Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\Listener\RegisterComponentDecoratorsListener
    public: true
    arguments:
      - []
      - []
    tags:
      - { name: 'contao.hook', hook: 'initializeSystem', method: 'onInitializeSystem', priority: 100 }

  netzmacht.contao_toolkit.listeners.register_models:
    class: Netzmacht\Contao\Toolkit\Bundle\DependencyInjection\Listener\RegisterContaoModelsListener
    public: true
    arguments:
      - []
    tags:
      - { name: 'contao.hook', hook: 'initializeSystem', method: 'onInitializeSystem', priority: 101 }

  netzmacht.contao_toolkit.listeners.set_operation_data_attribute:
    class: Netzmacht\Contao\Toolkit\Dca\Listener\SetOperationDataAttributeListener
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.routing.scope_matcher'
    tags:
      - { name: 'contao.hook', hook: 'loadDataContainer', method: 'onLoadDataContainer' }

  Netzmacht\Contao\Toolkit\Dca\Listener\Button\StateButtonCallbackListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.contao.backend_adapter'
      - '@netzmacht.contao_toolkit.contao.input_adapter'
      - '@netzmacht.contao_toolkit.data.database_row_updater'
      - '@netzmacht.contao_toolkit.dca.manager'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.state_button_callback:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Button\StateButtonCallbackListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener:
    public: true
    arguments:
      - '@service_container'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '%netzmacht.contao_toolkit.alias_generator.default%'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.alias_generator:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Save\GenerateAliasListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\ColorPickerListener:
    public: true
    arguments:
      - '@templating'
      - '@translator'
      - '@netzmacht.contao_toolkit.dca.manager'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.color_picker:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\ColorPickerListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\FilePickerListener:
    public: true
    arguments:
      - '@templating'
      - '@translator'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.contao.input_adapter'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.file_picker:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\FilePickerListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PagePickerListener:
    public: true
    arguments:
      - '@templating'
      - '@translator'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@netzmacht.contao_toolkit.contao.input_adapter'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.page_picker:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PagePickerListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PopupWizardListener:
    public: true
    arguments:
      - '@templating'
      - '@translator'
      - '@netzmacht.contao_toolkit.dca.manager'
      - '@security.csrf.token_manager'
      - '%contao.csrf_token_name%'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.popup_wizard:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PopupWizardListener
    public: true

  Netzmacht\Contao\Toolkit\Dca\Listener\Options\TemplateOptionsListener:
    public: true
    arguments:
      - '@netzmacht.contao_toolkit.dca.manager'

  # Deprecated. Marking aliases as deprecated is not supported yet https://github.com/symfony/symfony/issues/24507
  netzmacht.contao_toolkit.dca.listeners.template_options:
    alias: Netzmacht\Contao\Toolkit\Dca\Listener\Options\TemplateOptionsListener
    public: true
